fail-on-severity: moderate

comment-summary-in-pr: always

allow-licenses:
  - MIT
  - GPL-3.0
  - BSD-3-Clause

fail-on-scopes:
  - development
  - runtime
  - unknown

/* This configuration file is for the GitHub Dependency Review Action.
   For more information, see:
   https://docs.github.com/en/code-security/dependabot/dependency-review/dependency-review-action
*/